##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/pluma
    - appstream-glib
    - autoconf-archive
    - clang
    - enchant
    - file
    - gcc
    - git
    - gobject-introspection
    - gtksourceview4
    - iso-codes
    - itstool
    - libpeas
    - libsm
    - make
    - mate-common
    - python3
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/pluma
    - autopoint
    - autoconf-archive
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - gobject-introspection
    - gtk-doc-tools
    - iso-codes
    - libenchant-2-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-4-dev
    - libpeas-dev
    - libsm-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - python3-dev
    - python3-lxml
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/pluma.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - desktop-file-utils
    - enchant2-devel
    - gcc
    - git
    - gtk3-devel
    - gtksourceview4-devel
    - iso-codes-devel
    - libappstream-glib-devel
    - libSM-devel
    - libpeas1-devel
    - make
    - mate-common
    - pygobject3-devel
    - python3-devel
    - python3-lxml
    - redhat-rpm-config

  ubuntu:
    - autopoint
    - autoconf-archive
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - iso-codes
    - libenchant-2-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-4-dev
    - libpeas-dev
    - libsm-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - python3-dev
    - python3-lxml
    - yelp-tools

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - curl -Ls -o /usr/bin/gla11y https://github.com/hypra/gla11y/raw/v0.3/gla11y
  - chmod +x /usr/bin/gla11y

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: pluma-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
